###K-Fold Cross Validation End-organ comp code
setwd("/Volumes/Untitled 1/Backup")
library(tidyverse)
library(ggplot2)
library(ggsci)
library(mice)
library(caret)
library(rlist)
library(plotROC)
#Load, and do some reformatting i.e. factors etc...
for_risk<-read.csv("sdh_risk.csv", stringsAsFactors = FALSE)
for_risk$asa<-as.factor(for_risk$asa)
for_risk$mRS<-as.factor(for_risk$mRS)
for_risk$cog_cat<-as.factor(for_risk$cog_cat)
for_risk<-for_risk %>% select(-los_quant)
set.seed(123)

#This specifies variables that must and must not be included in the imputation models created by quickpred later
inlist<-c("nelson", "status", "prol_los", "end_organcomp")#specify that outcomes must be inclued in imputation model
outlist<-c("miss_mrs", "miss_asa", "miss_cog", "miss_creat")

fold_indices<-list()
split_dat<-list()
for (i in 1:10){
  fold_indices[[i]]<-createFolds(for_risk$age,k=10,returnTrain=FALSE)
  split_dat[[i]]<-lapply(fold_indices[[i]], function(ind, dat) dat[ind,], dat = for_risk)
  unlist(lapply(split_dat[[i]],nrow))
}
#specify MICE prediction model - same imputation model used in other file 
inlist<-c("nelson", "status", "prol_los", "end_organcomp")#specify that outcomes must be inclued in imputation model
outlist<-c("miss_mrs", "miss_asa", "miss_cog", "miss_creat")
missing_var_name<-c("asa", "cog_cat", "mRS", "last_creat")
pred<-quickpred(for_risk, minpuc=0.5, include=inlist, exclude=outlist)


head(for_risk)

imp_folds<-list()
mids_frames<-list()
fold_names<-c("Fold01", "Fold02", "Fold03", "Fold04", "Fold05", "Fold06", "Fold07", "Fold08", "Fold09", "Fold10")
count<-1
for (i in 1:10){
  temp<-split_dat[[i]]
for (fold in fold_names){
  j<-temp[[fold]]
  imp_folds[[fold]]<-mice(j, pred=pred, maxit=5,m=1)
}
  mids_frames[[count]]<-imp_folds
  count<-count+1
}

data_frames<-list ()
temp_frames<-list()
temp<-list()

fold_names<-c("Fold01", "Fold02", "Fold03", "Fold04", "Fold05", "Fold06", "Fold07", "Fold08", "Fold09", "Fold10")
for (i in 1:10){
  temp<-mids_frames[[i]]
for (fold in fold_names){
  temp_frames[[fold]]<-complete(temp[[fold]], "long", include=FALSE)
}
data_frames[[i]]<-temp_frames
}
}

finals<-list()
for (i in 1:10){
  temp<-data_frames[[i]]
for (fold in fold_names){
  finals[[i]]<-list.rbind(temp)
}
}

finals[[2]]
finals[[4]]



##Cross-validation loop
modpre_prol<-list()
coefs_preprol<-list()
modpre_end<-list()
coefs_pre_end<-list()
modpost_end<-list()
coefs_post_end<-list()
for (i in 1:10){
  dat<-finals[[i]]
  colnames(dat)<-make.names(colnames(dat), allow_ = FALSE)
  dat<-dat %>% mutate(end.organcomp = ifelse(end.organcomp==1, "Y", "N"))
  dat<-dat %>% mutate(Sex=ifelse(Sex=="M",1,ifelse(Sex=="F",0,Sex)))
  indices<-fold_indices[[i]]
  fitcontrol<-trainControl(method = "repeatedcv", index=NULL, indexOut=indices, classProbs=TRUE, savePredictions = T, summaryFunction =twoClassSummary)
 modpre_end[[i]]<-train(as.factor(end.organcomp)~asa+dgh.x+any.acoag+admission.comp, data=dat, method="glm", family=binomial(),trControl=fitcontrol, metric="ROC")
 coefs_pre_end[[i]]<-exp(summary(modpre_end[[i]])$coefficients)
 modpost_end[[i]]<-train(as.factor(end.organcomp)~asa+any.acoag+dos.comp+fent.equiv+co2.t+dgh.x, data=dat, method="glm", family=binomial(),trControl=fitcontrol, metric="ROC")
 coefs_post_end[[i]]<-exp(summary(modpre_end[[i]])$coefficients)
}

finals[[1]]


##DRAW A ROC CURVE

#Extract all predictions into one df of each cross validation

pre_end_preds<-list()
for (i in 1:10){
  pre_end_preds[[i]]<-modpre_end[[i]]$pred
}
pre_end_preds
pre_end_preds<-bind_rows(pre_end_preds, .id="column_label")

pre_end_roc<-ggplot(pre_end_preds, aes(m = Y, d=factor(obs, levels=c("Y", "N")), color=column_label))+geom_roc(hjust=-0.4,vjust=1.5, labels=FALSE, show.legend=FALSE)+coord_equal()+style_roc()+scale_color_jco()
pre_end_roc+labs(title="ROC curves generated by repeated cross-validation", subtitle = "Admission variables for identifying end-organ complications")

post_end_preds<-list()
for(i in 1:10){
  post_end_preds[[i]]<-modpost_end[[i]]$pred
}
post_end_preds<-bind_rows(post_end_preds, .id="column_label")

post_end_roc<-ggplot(post_end_preds, aes(m = Y, d=factor(obs, levels=c("Y", "N")), color=column_label))+geom_roc(hjust=-0.4,vjust=1.5, labels=FALSE, show.legend=FALSE)+coord_equal()+style_roc()+scale_color_jco()
post_end_roc+labs(title="ROC curves generated by repeated cross-validation", subtitle = "Day of surgery variables for identifying end-organ complications")

##Extract resampled values to allow generation of mean/CI etc...
resamps_pre_end<-resamples(modpre_end)
resamps_post_end<-resamples(modpost_end)

resamps_pre_end$ROC
roc_pre_end<-as.data.frame(summary(resamps_pre_end)$statistics$ROC)
roc_post_end<-as.data.frame(summary(resamps_post_end)$statistics$ROC)

roc_values<-cbind(roc_pre_end[,4],roc_post_end[,4])
colnames(roc_values)<-c("Pre_End_Organ", "Post_End_Organ")
roc_values
summary(roc_values)
sd(roc_values[,1])
sd(roc_values[,2])


#Export pictures
dev.off()
pre_end_roc
tiff(file="pre_roc.tiff", width = 12, height= 8 , units = "in", res = 300)
dev.off()
dev.off()
post_end_roc
tiff(file="post_roc.tiff", width = 12, height= 8 , units = "in", res = 300)
dev.off()
dev.off()
